name: Deploy to Docker Hub

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  deploy:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
        with:
          push: true
          file: ./Dockerfile
          target: runner
          tags: odrinwhite/dungeon-and-dungeon:latest
