name: Deploy to Docker Hub

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  deploy:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: true
          file: ./Dockerfile
          target: runner
          tags: odrinwhite/dungeon-and-dungeon:latest
